// export interface CryptoInfo {
//   ticker: string;
//   name: string;
//   sector: string;
// }

export const topCryptos = [
  { ticker: "BTC", name: "Bitcoin", sector: "Network / Store of Value" },
  { ticker: "ETH", name: "Ethereum", sector: "Network / Smart Contracts" },
  { ticker: "USDT", name: "Tether", sector: "Stablecoin" },
  { ticker: "BNB", name: "Binance Coin", sector: "Cefi / Exchange Token" },
  { ticker: "XRP", name: "XRP", sector: "Cefi / Payment Network" },
  { ticker: "USDC", name: "USD Coin", sector: "Stablecoin" },
  { ticker: "ADA", name: "Cardano", sector: "Network / Smart Contracts" },
  { ticker: "SOL", name: "Solana", sector: "Network / Smart Contracts" },
  { ticker: "DOGE", name: "Dogecoin", sector: "Cefi / Community Payments" },
  { ticker: "MATIC", name: "Polygon", sector: "Network / Layer‑2 Scaling" },
  { ticker: "DOT", name: "Polkadot", sector: "Network / Interoperability" },
  { ticker: "TRX", name: "TRON", sector: "Network / Smart Contracts" },
  { ticker: "AVAX", name: "Avalanche", sector: "Network / Smart Contracts" },
  { ticker: "SHIB", name: "Shiba Inu", sector: "Cefi / Community Meme" },
  { ticker: "WBTC", name: "Wrapped Bitcoin", sector: "Network / Tokenized BTC" },
  { ticker: "LTC", name: "Litecoin", sector: "Network / Payments" },
  { ticker: "UNI", name: "Uniswap", sector: "DeFi / Exchange" },
  { ticker: "LINK", name: "Chainlink", sector: "DeFi / Oracle" },
  { ticker: "FTT", name: "FTX Token", sector: "Cefi / Exchange Token" },
  { ticker: "ATOM", name: "Cosmos", sector: "Network / Interoperability" },
  { ticker: "XLM", name: "Stellar", sector: "Network / Payments" },
  { ticker: "MANA", name: "Decentraland", sector: "Gaming / Metaverse" },
  { ticker: "NEAR", name: "NEAR Protocol", sector: "Network / Smart Contracts" },
  { ticker: "APE", name: "ApeCoin", sector: "Cefi / Community Token" },
  { ticker: "ETC", name: "Ethereum Classic", sector: "Network / Smart Contracts" },
  { ticker: "ICP", name: "Internet Computer", sector: "Network / Smart Contracts" },
  { ticker: "FIL", name: "Filecoin", sector: "DeFi / Storage" },
  { ticker: "SAND", name: "The Sandbox", sector: "Gaming / Metaverse" },
  { ticker: "EGLD", name: "Elrond", sector: "Network / Smart Contracts" },
  { ticker: "XTZ", name: "Tezos", sector: "Network / Governance Chain" },
  { ticker: "AAVE", name: "Aave", sector: "DeFi / Lending Protocol" },
  { ticker: "MKR", name: "Maker", sector: "DeFi / Stablecoin" },
  { ticker: "AXS", name: "Axie Infinity", sector: "Gaming / NFT Game" },
  { ticker: "RPL", name: "Rocket Pool", sector: "DeFi / Staking" },
  { ticker: "GRT", name: "The Graph", sector: "DeFi / Data Indexing" },
  { ticker: "LUNC", name: "Terra Classic", sector: "Network / Smart Contracts" },
  { ticker: "FTM", name: "Fantom", sector: "Network / Smart Contracts" },
  { ticker: "SUSHI", name: "SushiSwap", sector: "DeFi / Exchange" },
  { ticker: "ALGO", name: "Algorand", sector: "Network / Smart Contracts" },
  { ticker: "RUNE", name: "THORChain", sector: "DeFi / Cross‑Chain" },
  { ticker: "CRV", name: "Curve DAO", sector: "DeFi / Stable Exchange" },
  { ticker: "QNT", name: "Quant", sector: "DeFi / Enterprise Blockchain" },
  { ticker: "GALA", name: "GALA", sector: "Gaming / Metaverse" },
  { ticker: "WAVES", name: "Waves", sector: "Network / Smart Contracts" },
  { ticker: "EOS", name: "EOS", sector: "Network / Smart Contracts" },
  { ticker: "KSM", name: "Kusama", sector: "Network / Experimental Chain" },
  { ticker: "ZEC", name: "Zcash", sector: "Privacy / Network" },
  { ticker: "BTG", name: "Bitcoin Gold", sector: "Network / Bitcoin Fork" },
  { ticker: "ENJ", name: "Enjin", sector: "Gaming / NFT Asset" },
  { ticker: "COTI", name: "COTI", sector: "DeFi / Payments" },
  { ticker: "PAXG", name: "PAX Gold", sector: "DeFi / Tokenized Gold" },
  { ticker: "DASH", name: "Dash", sector: "Network / Payments" },
  { ticker: "CHZ", name: "Chiliz", sector: "Cefi / Fan Tokens" },
  { ticker: "MIM", name: "Magic Internet Money", sector: "Stablecoin" },
  { ticker: "HBAR", name: "Hedera", sector: "Network / Enterprise Chain" },
  { ticker: "ONT", name: "Ontology", sector: "Network / Enterprise Chain" },
  { ticker: "IOST", name: "IOST", sector: "Network / Smart Contracts" },
  { ticker: "NEO", name: "NEO", sector: "Network / Smart Contracts" },
  { ticker: "GNO", name: "Gnosis", sector: "DeFi / MultiSig Wallet" },
  { ticker: "ZIL", name: "Zilliqa", sector: "Network / Smart Contracts" },
  { ticker: "CEL", name: "Celsius", sector: "DeFi / Lending" },
  { ticker: "VET", name: "VeChain", sector: "Enterprise / Supply Chain" },
  { ticker: "XMR", name: "Monero", sector: "Privacy / Network" },
  { ticker: "DCR", name: "Decred", sector: "Network / Governance" },
  { ticker: "RAY", name: "Raydium", sector: "DeFi / Solana AMM" },
  { ticker: "1INCH", name: "1inch", sector: "DeFi / Aggregator" },
  { ticker: "OMG", name: "OMG Network", sector: "Network / Layer‑2 Scaling" },
  { ticker: "SXP", name: "Swipe", sector: "Cefi / Payments" },
  { ticker: "HOT", name: "Holo", sector: "Network / Distributed Hosting" },
  { ticker: "KNC", name: "Kyber Network", sector: "DeFi / Aggregator" },
  { ticker: "HNT", name: "Helium", sector: "IoT / Network" },
  { ticker: "AMP", name: "Amp", sector: "DeFi / Collateral" },
  { ticker: "BAT", name: "Basic Attention Token", sector: "Cefi / Ad Network" },
  { ticker: "ANKR", name: "Ankr", sector: "Network / Infrastructure" },
  { ticker: "SC", name: "Siacoin", sector: "DeFi / Storage" },
  { ticker: "RVN", name: "Ravencoin", sector: "Network / Asset Transfer" },
  { ticker: "NEXO", name: "Nexo", sector: "DeFi / Lending" },
  { ticker: "COMP", name: "Compound", sector: "DeFi / Lending" },
  { ticker: "KAVA", name: "Kava", sector: "DeFi" },
  { ticker: "SNX", name: "Synthetix", sector: "DeFi / Derivatives" },
  { ticker: "UMA", name: "UMA", sector: "DeFi / Derivatives" },
  { ticker: "CVC", name: "Civic", sector: "Network / Identity" },
  { ticker: "LUNA", name: "Terra", sector: "Network / Smart Contracts" },
  { ticker: "CAKE", name: "PancakeSwap", sector: "DeFi / Exchange" }
];